ALTER TABLE QUESTION ALTER COLUMN ID BIGINT DEFAULT NOT NULL;
ALTER TABLE USER ALTER COLUMN ID BIGINT DEFAULT NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN CREATOR BIGINT ;
ALTER TABLE COMMENT ALTER COLUMN COMMENTATOR BIGINT ;